EcmsWebApplication/EcmsWebApplication/Controllers/CouponsBatchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EcmsModels.DataModels;
using EcmsBusinessLogic;
using EcmsModels.WebModels;

namespace EcmsWebApplication.Controllers
{
    [Authorize]
    public class CouponsBatchController : Controller
    {
        private EcmsDbContext db = new EcmsDbContext();

        // GET: CouponsBatch
        public async Task<ActionResult> Index()
        {
            var CouponsBatch = db.CouponsBatch.Include(c => c.CouponsBatchTransfers).Include(c => c.SubSection).Include(c => c.FuelType).Include(c => c.ParentBatch).Include(c => c.CouponBatchStatus);
            return View(await CouponsBatch.ToListAsync());
        }

        // GET: CouponsBatch
        public async Task<ActionResult> ChildIndex(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var CouponsBatch = db.CouponsBatch.Where(e => e.ParentBatchId == id).Include(c => c.CouponsBatchTransfers).Include(c => c.SubSection).Include(c => c.FuelType).Include(c => c.ParentBatch).Include(c => c.CouponBatchStatus);
            return View("Index", await CouponsBatch.ToListAsync());
        }

        // GET: CouponsBatch/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CouponsBatch couponsBatch = await db.CouponsBatch.FindAsync(id);
            if (couponsBatch == null)
            {
                return HttpNotFound();
            }
            return View(couponsBatch);
        }

        // GET: CouponsBatch/Create
        public ActionResult Create(int subSectionId)
        {
            var user = new ApplicationUser().GetByUsername(User.Identity.Name);
            ViewBag.ParentBatchId = new SelectList(db.CouponsBatch.Where(e => e.SubSectionId == user.SubSectionId && !e.IsArchivable && !e.IsInTransit), "Id", "Id");
            var couponBatch = new CouponsBatch();
            couponBatch.SubSectionId = user.SubSectionId;
            couponBatch.Id = "Temp Id";
            couponBatch.BookSize = 1;
            couponBatch.Denomination = 1;
            return View(couponBatch);
        }

        // GET: CouponsBatch/Create
        public ActionResult DirectCreate(int subSectionId, string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.ParentBatchId = new SelectList(db.CouponsBatch.Where(e => e.SubSectionId == subSectionId && !e.IsArchivable && !e.IsInTransit), "Id", "Id", id);
            var couponBatch = new CouponsBatch();
            couponBatch.SubSectionId = subSectionId;
            couponBatch.Id = "Temp Id";
            couponBatch.BookSize = 1;
            couponBatch.Denomination = 1;
            return View("Create", couponBatch);
        }

        // POST: CouponsBatch/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,ParentBatchId,SubSectionId,BookSize,FuelTypeId,Denomination,BatchSize,DateCreated,ExpiryDate,Issuer,CreatedBy,Description,StatusId,Notes")] CouponsBatch couponsBatch)
        {
            ViewBag.ParentBatchId = new SelectList(db.CouponsBatch.Where(e => e.SubSectionId ==couponsBatch.SubSectionId), "Id", "Id");
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(couponsBatch.ParentBatchId))
                {
                    if (couponsBatch.BatchSize > 0)
                    {
                        var parentBatch = await db.CouponsBatch.FindAsync(couponsBatch.ParentBatchId);
                        if (parentBatch != null)
                        {
                            if (parentBatch.BatchSize > couponsBatch.BatchSize)
                            {
                                var creator = new ApplicationUser().GetByUsername(User.Identity.Name);
                                parentBatch.BatchSize -= couponsBatch.BatchSize;
                                var numericParentBatchId = BusinessLogic.GetNumericCouponNumber(parentBatch.Id);
                                var numericNewBatchId = numericParentBatchId + parentBatch.BatchSize;
                                couponsBatch.Id = BusinessLogic.GetStringCouponNumber(parentBatch.Id, numericNewBatchId);
                                couponsBatch.BookSize = parentBatch.BookSize;
                                couponsBatch.CouponIssuerId = parentBatch.CouponIssuerId;
                                couponsBatch.CreatedBy = creator.Id;
                                couponsBatch.DateCreated = DateTime.Now.GetCondensedDateTime();
                                couponsBatch.Denomination = parentBatch.Denomination;
                                couponsBatch.ExpiryDate = parentBatch.ExpiryDate;
                                couponsBatch.FuelTypeId = parentBatch.FuelTypeId;
                                couponsBatch.IsArchivable = false;
                                couponsBatch.StatusId = parentBatch.StatusId;
                                couponsBatch.SubSectionId = parentBatch.SubSectionId;
                                db.CouponsBatch.Add(couponsBatch);
                                await db.SaveChangesAsync();
                                return RedirectToAction("Index");
                            }
                            ModelState.AddModelError("", "The parent batch does not have sufficient coupons for this child batch to be created.");
                            return View(couponsBatch);
                        }
                        ModelState.AddModelError("", "The specified parent batch was not found.");
                        return View(couponsBatch);
                    }
                    ModelState.AddModelError("", "The parent batch was not specified.");
                    return View(couponsBatch);
                }
                ModelState.AddModelError("", "Invalid batch size.");
                return View(couponsBatch);
            }
            return View(couponsBatch);
        }

        // GET: CouponsBatch/StockIn
        public ActionResult StockIn()
        {
            //ViewBag.Id = new SelectList(db.CouponsBatchTransfer, "BatchId", "TransferredBy");
            //ViewBag.DepartmentId = new SelectList(db.Department, "Id", "Name");
            //ViewBag.ParentBatchId = new SelectList(db.CouponsBatch.Where(e => e.SubSectionId == subSectionId), "Id", "Issuer");
            ViewBag.FuelTypeId = new SelectList(db.FuelType, "Id", "Name");
            ViewBag.StatusId = new SelectList(db.CouponBatchStatus, "Id", "Description");
            ViewBag.CouponIssuerId = new SelectList(db.CouponIssuer, "Id", "Name");

            return View();
        }

        // POST: CouponsBatch/StockIn
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> StockIn([Bind(Include = "Id,ParentBatchId,DepartmentId,BookSize,FuelTypeId,Denomination,BatchSize,DateCreated,ExpiryDate,CouponIssuerId,CreatedBy,Description,StatusId,Notes")] CouponsBatch couponsBatch)
        {
            couponsBatch.Id = couponsBatch.Id.Replace(" ", "").Trim().ToUpper();
            ViewBag.FuelTypeId = new SelectList(db.FuelType, "Id", "Name", couponsBatch.FuelTypeId);
            ViewBag.StatusId = new SelectList(db.CouponBatchStatus, "Id", "Description", couponsBatch.StatusId);
            ViewBag.CouponIssuerId = new SelectList(db.CouponIssuer, "Id", "Name", couponsBatch.CouponIssuerId);
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(couponsBatch.Id))
                {
                    var check = await db.CouponsBatch.FindAsync(couponsBatch.Id);
                    if (check == null)
                    {
                        var creator = new ApplicationUser().GetByUsername(User.Identity.Name);
                        couponsBatch.DateCreated = DateTime.Now.GetCondensedDateTime();
                        couponsBatch.CreatedBy = creator.Id;
                        couponsBatch.ParentBatchId = couponsBatch.Id;
                        couponsBatch.IsArchivable = false;
                        couponsBatch.SubSectionId = creator.SubSectionId;

                        db.CouponsBatch.Add(couponsBatch);
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index");
                    }
                    ModelState.AddModelError("", $"A batch with the same Batch Number already exists.");
                    return View(couponsBatch);
                }
                ModelState.AddModelError("", $"Please specify a batch number.");
                return View(couponsBatch);
            }
            return View(couponsBatch);
        }

        //// GET: CouponsBatch/Edit/5
        //public async Task<ActionResult> Edit(long? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    CouponsBatch couponsBatch = await db.CouponsBatch.FindAsync(id);
        //    if (couponsBatch == null)
        //    {
        //        return HttpNotFound();
        //    }

EcmsWebApplication/EcmsWebApplication/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using EcmsBusinessLogic;
using EcmsModels.DataModels;
using EcmsWebApplication.Models;

namespace EcmsWebApplication.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private EcmsDbContext db = new EcmsDbContext();
        public static DepartmentViewModel departmentDynamicViewModel = new DepartmentViewModel();

        // GET: Department
        public ActionResult Index()
        {
            var departments = db.Department;
            return View(departments.ToList());
        }

        // GET: Department/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Department.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);

        }

        // GET: Department/Create
        public ActionResult Create()
        {
            ViewBag.OverseerUserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Department/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Department department)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.OverseerUserId = new SelectList(db.Users, "Id", "Email");
                return View(department);
            }
            try
            {
                var result = db.Department.SingleOrDefault(d => d.Name == department.Name);
                if (result == null)
                {
                    db.Department.Add(department);
                    db.SaveChanges();
                    var defaultSection = Section.CreateDefault(department);
                    db.SaveChanges();
                    var defaultSubSection = SubSection.CreateDefault(defaultSection);
                    db.SubSection.Add(defaultSubSection);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "A Department with the same name already exists.");
                ViewBag.OverseerUserId = new SelectList(db.Users, "Id", "Email", department.OverseerUserId);
                return View(department);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                ViewBag.OverseerUserId = new SelectList(db.Users, "Id", "Email", department.OverseerUserId);
                return View();
            }
        }

        // GET: Department/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var department = db.Department.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            ViewBag.OverseerUserId = new SelectList( department.GetUsers(), "Id", "Email", department.OverseerUserId );
            return View(department);
        }

        // POST: Department/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Department department)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.OverseerUserId = new SelectList(department.GetUsers(), "Id", "Email", department.OverseerUserId);
                return View(department);
            }
            try
            {
                var oldDepartment = db.Department.Find(department.Id);
                if (oldDepartment != null)
                {
                    var result = db.Department.SingleOrDefault(d => d.Name == department.Name && d.Id != department.Id);
                    if (result == null)
                    {
                        db.Entry(oldDepartment).State = System.Data.Entity.EntityState.Detached;
                        db.Entry(department).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    ModelState.AddModelError("", "A department with the same name already exists.");
                    ViewBag.OverseerUserId = new SelectList(department.GetUsers(), "Id", "Email", department.OverseerUserId);
                    return View(department);
                }
                ModelState.AddModelError("", "The specified department no longer exists.");
                ViewBag.OverseerUserId = new SelectList(department.GetUsers(), "Id", "Email", department.OverseerUserId);
                return View(department);
            }
            catch(Exception e)
            {
                ModelState.AddModelError("", e.Message);
                ViewBag.OverseerUserId = new SelectList(department.GetUsers(), "Id", "Email", department.OverseerUserId);
                return View(department);
            }
        }

        public ActionResult DepartmentPartial()
        {
            departmentDynamicViewModel.EntityList.Clear();
            departmentDynamicViewModel.EntityList.AddRange(db.Department);
            return View(departmentDynamicViewModel);
        }

        //// GET: Department/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: Department/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

EcmsWebApplication/EcmsWebApplication/Views/CouponsBatch/Create.cshtml
@model EcmsModels.DataModels.CouponsBatch

@{
    ViewBag.Title = "New Coupons Batch";
}

@using (Html.BeginForm("Create","CouponsBatch"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @*<h4>@ViewBag.Title</h4>*@
    <div>
        @Html.ActionLink(" ", "Index", null, new { @class = "fa fa-arrow-left" })
    </div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.SubSectionId)
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.BookSize)
    @Html.HiddenFor(model => model.Denomination)

    <div class="form-group">
        @Html.LabelFor(model => model.ParentBatchId, "Parent Batch", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ParentBatchId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ParentBatchId, "", new { @class = "text-danger" })
        </div>
    </div>

    @*@Html.Action("DepartmentPartial", "Department")
        @Html.Action("SectionPartial", "Sections")*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.SubSectionId, "SubSectionId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubSectionId", null, htmlAttributes: new { @id = "SubSection", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubSectionId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.BookSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookSize, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.FuelTypeId, "FuelTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FuelTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FuelTypeId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.Denomination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Denomination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Denomination, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.BatchSize, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BatchSize, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BatchSize, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpiryDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpiryDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.CouponIssuer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CouponIssuerId", null, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CouponIssuer, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryunobtrusiveajax")
    @Scripts.Render("~/bundles/dynamicdropdown")
}

EcmsWebApplication/EcmsWebApplication/Views/CouponsBatch/Edit.cshtml
@model EcmsModels.DataModels.CouponsBatch

@{
    ViewBag.Title = "Edit Coupons Batch";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@ViewBag.Title</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ParentBatchId, "ParentBatchId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ParentBatchId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParentBatchId, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.Action("DepartmentPartial", "Department")
        @Html.Action("SectionPartial", "Sections")

        <div class="form-group">
            @Html.LabelFor(model => model.SubSectionId, "SubSectionId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubSectionId", null, htmlAttributes: new { @id = "SubSection", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubSectionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FuelTypeId, "FuelTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FuelTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FuelTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Denomination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Denomination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Denomination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BatchSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BatchSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BatchSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpiryDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpiryDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CouponIssuerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CouponIssuerId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CouponIssuerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryunobtrusiveajax")
    @Scripts.Render("~/bundles/dynamicdropdown")
}