EcmsWebApplication/EcmsWebApplication/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using EcmsBusinessLogic;
using EcmsModels.DataModels;
using EcmsWebApplication.Models;

namespace EcmsWebApplication.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private EcmsDbContext db = new EcmsDbContext();
        public static DepartmentViewModel departmentDynamicViewModel = new DepartmentViewModel();

        // GET: Department
        public ActionResult Index()
        {
            var departments = db.Department;
            return View(departments.ToList());
        }

        // GET: Department/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Department.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);

        }

        // GET: Department/Create
        public ActionResult Create()
        {
            ViewBag.OverseerUserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Department/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Department department)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.OverseerUserId = new SelectList(db.Users, "Id", "Email");
                return View(department);
            }
            try
            {
                var result = db.Department.SingleOrDefault(d => d.Name == department.Name);
                if (result == null)
                {
                    db.Department.Add(department);
                    db.SaveChanges();
                    var defaultSection = Section.CreateDefault(department);
                    db.SaveChanges();
                    var defaultSubSection = SubSection.CreateDefault(defaultSection);
                    db.SubSection.Add(defaultSubSection);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "A Department with the same name already exists.");
                ViewBag.OverseerUserId = new SelectList(db.Users, "Id", "Email", department.OverseerUserId);
                return View(department);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                ViewBag.OverseerUserId = new SelectList(db.Users, "Id", "Email", department.OverseerUserId);
                return View();
            }
        }

        // GET: Department/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var department = db.Department.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            ViewBag.OverseerUserId = new SelectList( department.GetUsers(), "Id", "Email", department.OverseerUserId );
            return View(department);
        }

        // POST: Department/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Department department)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.OverseerUserId = new SelectList(department.GetUsers(), "Id", "Email", department.OverseerUserId);
                return View(department);
            }
            try
            {
                var oldDepartment = db.Department.Find(department.Id);
                if (oldDepartment != null)
                {
                    var result = db.Department.SingleOrDefault(d => d.Name == department.Name && d.Id != department.Id);
                    if (result == null)
                    {
                        db.Entry(oldDepartment).State = System.Data.Entity.EntityState.Detached;
                        db.Entry(department).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    ModelState.AddModelError("", "A department with the same name already exists.");
                    ViewBag.OverseerUserId = new SelectList(department.GetUsers(), "Id", "Email", department.OverseerUserId);
                    return View(department);
                }
                ModelState.AddModelError("", "The specified department no longer exists.");
                ViewBag.OverseerUserId = new SelectList(department.GetUsers(), "Id", "Email", department.OverseerUserId);
                return View(department);
            }
            catch(Exception e)
            {
                ModelState.AddModelError("", e.Message);
                ViewBag.OverseerUserId = new SelectList(department.GetUsers(), "Id", "Email", department.OverseerUserId);
                return View(department);
            }
        }

        public ActionResult DepartmentPartial()
        {
            departmentDynamicViewModel.EntityList.Clear();
            departmentDynamicViewModel.EntityList.AddRange(db.Department);
            return View(departmentDynamicViewModel);
        }

        //// GET: Department/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: Department/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

EcmsWebApplication/EcmsWebApplication/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EcmsModels.DataModels;
using EcmsWebApplication.Models;

namespace EcmsWebApplication.Controllers
{
    [Authorize]
    public class SectionsController : Controller
    {
        private EcmsDbContext db = new EcmsDbContext();
        public static SectionViewModel sectionDynamicViewModel = new SectionViewModel();

        // GET: Sections
        public async Task<ActionResult> Index()
        {
            var section = db.Section.Include(s => s.Department);
            return View(await section.ToListAsync());
        }

        // GET: Sections/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = await db.Section.FindAsync(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // GET: Sections/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Department, "Id", "Name");
            ViewBag.OverseerUserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Sections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,OverseerUserId,Disabled,Notes,DepartmentId")] Section section)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.DepartmentId = new SelectList(db.Department, "Id", "Name", section.DepartmentId);
                ViewBag.OverseerUserId = new SelectList(db.Users, "Id", "Email", section.OverseerUserId);
                return View(section);
            }
            try
            {
                var department = await db.Department.FindAsync(section.DepartmentId);
                if(department != null)
                {
                    var result = department.Sections.SingleOrDefault(d => d.Name == section.Name);
                    if (result == null)
                    {
                        db.Section.Add(section);
                        await db.SaveChangesAsync();
                        var defaultSubSection = SubSection.CreateDefault(section);
                        db.SubSection.Add(defaultSubSection);
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index");
                    }
                    ModelState.AddModelError("", $"A Section with the same name already exists in the {department.Name} department.");
                    ViewBag.OverseerUserId = new SelectList(db.Users, "Id", "Email", section.OverseerUserId);
                    ViewBag.DepartmentId = new SelectList(db.Department, "Id", "Name", section.DepartmentId);
                    return View(section);
                }
                ModelState.AddModelError("", "The department you specified no longer exists.");
                ViewBag.OverseerUserId = new SelectList(db.Users, "Id", "Email", section.OverseerUserId);
                ViewBag.DepartmentId = new SelectList(db.Department, "Id", "Name", section.DepartmentId);
                return View(section);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                ViewBag.OverseerUserId = new SelectList(db.Users, "Id", "Email", section.OverseerUserId);
                ViewBag.DepartmentId = new SelectList(db.Department, "Id", "Name", section.DepartmentId);
                return View();
            }
        }

        // GET: Sections/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = await db.Section.FindAsync(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartmentId = new SelectList(db.Department, "Id", "Name", section.DepartmentId);
            ViewBag.OverseerUserId = new SelectList(section.GetUsers(), "Id", "Email", section.OverseerUserId);
            return View(section);
        }

        // POST: Sections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,OverseerUserId,Disabled,Notes,DepartmentId")] Section section)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.DepartmentId = new SelectList(db.Department, "Id", "Name", section.DepartmentId);
                ViewBag.OverseerUserId = new SelectList(section.GetUsers(), "Id", "Email", section.OverseerUserId);
                return View(section);
            }
            try
            {
                var oldSection = await db.Section.FindAsync(section.Id);
                if (oldSection != null)
                {
                    var result = oldSection.Department.Sections.SingleOrDefault(d => d.Name == section.Name && d.Id != section.Id);
                    if (result == null)
                    {
                        db.Entry(oldSection).State = System.Data.Entity.EntityState.Detached;
                        db.Entry(section).State = EntityState.Modified;
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index");
                    }
                    ModelState.AddModelError("", $"A Section already exists with the same name in the {oldSection.Department.Name}.");
                    ViewBag.OverseerUserId = new SelectList(section.GetUsers(), "Id", "Email", section.OverseerUserId);
                    ViewBag.DepartmentId = new SelectList(db.Department, "Id", "Name", section.DepartmentId);
                    return View(section);
                }
                ModelState.AddModelError("", "The specified Section no longer exists.");
                ViewBag.DepartmentId = new SelectList(db.Department, "Id", "Name", section.DepartmentId);
                ViewBag.OverseerUserId = new SelectList(section.GetUsers(), "Id", "Email", section.OverseerUserId);
                return View(section);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                ViewBag.DepartmentId = new SelectList(db.Department, "Id", "Name", section.DepartmentId);
                ViewBag.OverseerUserId = new SelectList(section.GetUsers(), "Id", "Email", section.OverseerUserId);
                return View(section);
            }




            db.Entry(section).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public ActionResult SectionPartial(int? departmentId)
        {
            sectionDynamicViewModel.EntityList.Clear();
            if (departmentId != null)
            {
                var department = db.Department.Find(departmentId);
                sectionDynamicViewModel.EntityList.AddRange(department.Sections);
            }
            return View(sectionDynamicViewModel);
        }

        public ActionResult SectionView(int? departmentId)
        {
            sectionDynamicViewModel.EntityList.Clear();
            if (departmentId != null)
            {
                var department = db.Department.Find(departmentId);
                sectionDynamicViewModel.EntityList.AddRange(department.Sections);
            }
            return Json(sectionDynamicViewModel.EntitySelectList, JsonRequestBehavior.AllowGet);
        }

        //// GET: Sections/Delete/5
        //public async Task<ActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Section section = await db.Section.FindAsync(id);
        //    if (section == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(section);
        //}

        //// POST: Sections/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteConfirmed(int id)
        //{
        //    Section section = await db.Section.FindAsync(id);
        //    db.Section.Remove(section);
        //    await db.SaveChangesAsync();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EcmsWebApplication/EcmsWebApplication/Views/MaintenanceCentres/Create.cshtml
@model EcmsModels.DataModels.MaintenanceCentre

@{
    ViewBag.Title = "New Maintenance Centre";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@ViewBag.Title</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OverseerUserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("OverseerUserId", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.OverseerUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Disabled, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Disabled)
                    @Html.ValidationMessageFor(model => model.Disabled, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.Action("DepartmentPartial", "Department")
        @Html.Action("SectionPartial", "Sections")
        @Html.Action("SubSectionPartial", "SubSections")

        <div class="form-group">
            @Html.LabelFor(model => model.SubZoneId, "SubZoneId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubZoneId", null, htmlAttributes: new { @id = "SubZone", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubZoneId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryunobtrusiveajax")
    @Scripts.Render("~/bundles/dynamicdropdown")
}

EcmsWebApplication/EcmsWebApplication/Views/MaintenanceCentres/Delete.cshtml
@model EcmsModels.DataModels.MaintenanceCentre

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MaintenanceCentre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SubZone.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubZone.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OverseerUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OverseerUserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Disabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Disabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EcmsWebApplication/EcmsWebApplication/Views/MaintenanceCentres/Details.cshtml
@model EcmsModels.DataModels.MaintenanceCentre

@{
    ViewBag.Title = "Maintenance Centre Details";
}

<div>
    <h4>@ViewBag.Title</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SubZone.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubZone.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OverseerUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GetOverseer().FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Disabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Disabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EcmsWebApplication/EcmsWebApplication/Views/MaintenanceCentres/Edit.cshtml
@model EcmsModels.DataModels.MaintenanceCentre

@{
    ViewBag.Title = "Edit Maintenance Centre";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>@ViewBag.Title</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OverseerUserId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("OverseerUserId", null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OverseerUserId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Disabled, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Disabled)
                @Html.ValidationMessageFor(model => model.Disabled, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.Action("DepartmentPartial", "Department")
    @Html.Action("SectionPartial", "Sections")
    @Html.Action("SubSectionPartial", "SubSections")


    <div class="form-group">
        @Html.LabelFor(model => model.SubZoneId, "SubZoneId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("SubZoneId", null, htmlAttributes: new { @id = "SubZone", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SubZoneId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryunobtrusiveajax")
    @Scripts.Render("~/bundles/dynamicdropdown")
}

EcmsWebApplication/EcmsWebApplication/Views/MaintenanceCentres/Index.cshtml
@model IEnumerable<EcmsModels.DataModels.MaintenanceCentre>

@{
    ViewBag.Title = "Maintenance Centres";
}

<h4>@ViewBag.Title</h4>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SubZone.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OverseerUserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Disabled)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Notes)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SubZone.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GetOverseer().FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Disabled)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Notes)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id })
        </td>
    </tr>
}

</table>